name: GrimAC
version: 2.3.69
main: ac.grim.grimac.GrimAC
author: GrimAC
website: https://grim.ac/
api-version: 1.13
folia-supported: true
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - Essentials
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
  - floodgate
  - FastLogin
  - PlaceholderAPI
permissions:
  grim.alerts:
    description: Receive alerts for violations
    default: op
  grim.alerts.enable-on-join:
    description: Enable alerts on join
    default: op
  grim.performance:
    description: Check performance metrics
    default: op
  grim.profile:
    description: Check user profile
    default: op
  grim.brand:
    description: Show client brands on join
    default: op
  grim.brand.enable-on-join:
    description: Enable showing client brands on join
    default: op
  grim.brand.exempt:
    description: Do not show this player's client brand
    default: op
  grim.sendalert:
    description: Send cheater alert
    default: op
  grim.nosetback:
    description: Disable setback
    default: false
  grim.nomodifypacket:
    description: Disable modifying packets
    default: false
  grim.exempt:
    description: Exempt from all checks
    default: false
  grim.verbose:
    description: Receive verbose alerts for violations. Requires grim.alerts
    default: op
  grim.verbose.enable-on-join:
    description: Enable verbose alerts on join. Requires grim.alerts and grim.alerts.enable-on-join
    default: false
